import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "@/providers/ReduxProvider";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import MarginContainer from "@/components/common/MarginContainer";
import AuthProvider from "@/providers/AuthProvider";
import { Toaster } from "react-hot-toast";
import GlobalLoader from "@/components/common/GlobalLoader";
import SessionExpiredModal from "@/components/common/SessionExpiredModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${geistSans.variable} ${geistMono.variable}`}
    >
      <body className="flex flex-col min-h-screen bg-base-200">
        <ReduxProvider>
          <AuthProvider>
            <GlobalLoader />
            <SessionExpiredModal />
            <Header />
            <main className="flex-grow">
              <MarginContainer>{children}</MarginContainer>
              <Toaster position="top-center" />
            </main>
            <Footer />
          </AuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
