-- ============================================
-- Stripe Events Table
-- ============================================

CREATE TABLE stripe_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    stripe_event_id VARCHAR(255) NOT NULL,
    event_type VARCHAR(255) NOT NULL,

    payment_id BIGINT,
    processed_at TIMESTAMP NOT NULL,

    version BIGINT DEFAULT 0 NOT NULL,

    CONSTRAINT uk_stripe_events_event_id UNIQUE (stripe_event_id),

    CONSTRAINT fk_stripe_events_payment
        FOREIGN KEY (payment_id)
        REFERENCES payments (id)
        ON DELETE SET NULL
);


-- ============================================
-- Envers Audit Table
-- ============================================

CREATE TABLE stripe_events_aud (
    id BIGINT NOT NULL,
    rev INTEGER NOT NULL,
    revtype SMALLINT,

    stripe_event_id VARCHAR(255),
    event_type VARCHAR(255),
    payment_id BIGINT,
    processed_at TIMESTAMP,
    version BIGINT,

    PRIMARY KEY (id, rev),

    CONSTRAINT fk_stripe_events_aud_rev
        FOREIGN KEY (rev)
        REFERENCES revinfo (rev)
);
