CREATE TABLE homepage_configs (
    id BIGSERIAL PRIMARY KEY,
    hero_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    hero_title VARCHAR(255),
    hero_subtitle VARCHAR(1000),
    hero_button_text VARCHAR(120),
    hero_button_link VARCHAR(500),
    hero_content_position VARCHAR(30) NOT NULL DEFAULT 'LEFT',
    hero_image_url VARCHAR(500),
    hero_text_color_mode VARCHAR(30) NOT NULL DEFAULT 'AUTO',
    hero_custom_text_color VARCHAR(20),
    hero_overlay_strength INTEGER NOT NULL DEFAULT 42,
    featured_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    featured_title VARCHAR(255),
    featured_selection_mode VARCHAR(30) NOT NULL DEFAULT 'RANDOM',
    featured_tour_ids_json TEXT NOT NULL DEFAULT '[]',
    featured_max_items INTEGER NOT NULL DEFAULT 8,
    highlighted_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    highlighted_title VARCHAR(255),
    highlighted_selection_mode VARCHAR(30) NOT NULL DEFAULT 'RANDOM',
    highlighted_tour_ids_json TEXT NOT NULL DEFAULT '[]',
    collection_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    collection_title VARCHAR(255),
    collection_blocks_json TEXT NOT NULL DEFAULT '[]',
    value_section_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    value_eyebrow VARCHAR(120),
    value_title VARCHAR(255),
    value_description VARCHAR(1000),
    value_cards_json TEXT NOT NULL DEFAULT '[]',
    about_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    about_eyebrow VARCHAR(120),
    about_title VARCHAR(255),
    about_description VARCHAR(1000),
    about_button_text VARCHAR(120),
    cta_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    cta_title VARCHAR(255),
    cta_description VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_homepage_configs_singleton CHECK (id = 1)
);

INSERT INTO homepage_configs (
    id,
    hero_enabled,
    hero_title,
    hero_subtitle,
    hero_button_text,
    hero_button_link,
    hero_content_position,
    hero_image_url,
    hero_text_color_mode,
    hero_overlay_strength,
    featured_enabled,
    featured_title,
    featured_selection_mode,
    featured_tour_ids_json,
    featured_max_items,
    highlighted_enabled,
    highlighted_title,
    highlighted_selection_mode,
    highlighted_tour_ids_json,
    collection_enabled,
    collection_title,
    collection_blocks_json,
    value_section_enabled,
    value_eyebrow,
    value_title,
    value_description,
    value_cards_json,
    about_enabled,
    about_eyebrow,
    about_title,
    about_description,
    about_button_text,
    cta_enabled,
    cta_title,
    cta_description
)
SELECT
    1,
    TRUE,
    'Find your adventure',
    'Guided tours shaped for easier browsing, clearer details, and faster decisions',
    'Browse all tours',
    '/items',
    'LEFT',
    '/images/welcome_image.png',
    'AUTO',
    42,
    TRUE,
    'Featured tours',
    'RANDOM',
    '[]',
    8,
    TRUE,
    'Tour spotlight',
    'RANDOM',
    '[]',
    TRUE,
    'Explore by style',
    '[{"badge":"City pace","title":"Walking routes","description":"Shorter-format experiences for exploring neighborhoods, landmarks, and local stories on foot.","category":"WALKING","tourId":null},{"badge":"Nature focus","title":"Outdoor escapes","description":"Trails, scenic routes, and fresh-air experiences built for travelers who want room to roam.","category":"HIKING","tourId":null},{"badge":"Stories first","title":"Culture trails","description":"History, art, and local context grouped into tours made for slower, more thoughtful discovery.","category":"CULTURE","tourId":null},{"badge":"Social energy","title":"Food and evening picks","description":"Browse tours that lean into tastings, nightlife, and memorable shared moments after the daytime rush.","category":"FOOD","tourId":null}]',
    TRUE,
    'Why book here',
    'A homepage built to make comparing tours feel quicker and more considered',
    'The homepage is designed to surface the details that matter early, so it is easier to compare routes, pacing, group format, and booking fit before you commit.',
    '[{"title":"Curated routes","description":"Compare city walks, nature outings, and themed experiences from one place instead of juggling separate listings.","iconKey":"COMPASS"},{"title":"Flexible group options","description":"Public and private formats sit side by side so it is easier to choose the right pace and group size.","iconKey":"USERS"},{"title":"Straightforward booking","description":"Search by date, review the essentials quickly, and move into booking without extra friction.","iconKey":"SHIELD_CHECK"},{"title":"Useful details upfront","description":"Duration, intensity, languages, and meeting context stay visible while you browse and compare.","iconKey":"TIMER_RESET"}]',
    TRUE,
    'About the platform',
    'Tour discovery designed to feel clearer from the first click',
    'From quick city walks to longer outdoor routes, the goal is to make it easier to understand each experience, compare options, and move into booking with confidence.',
    'Explore tours',
    TRUE,
    'Ready to find the right tour or ask a question before you book?',
    'Keep browsing the tour catalog, or head to the contact page if you want help choosing a route, comparing options, or planning a trip.'
WHERE NOT EXISTS (
    SELECT 1
    FROM homepage_configs
);

SELECT setval(
    pg_get_serial_sequence('homepage_configs', 'id'),
    COALESCE((SELECT MAX(id) FROM homepage_configs), 1),
    true
);
